# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51934ca68ec017c2d22887261acad4d711e0017c02531c9766efef8caa5b7d7261abfcc5541fe7c2296f8fa0f0c62cb696a3801740b364ebed35a851c33f0eb6

test:
  secret_key_base: d4347acefe4afdde4244a4b709ac286e44719ea1781b21ed927844a6b1bdfdff359584772307db6c7ee5943ba27264654a586183b3f44a844615c3b8e774d01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
